# Generated by Django 2.1 on 2018-08-24 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedModel',
        ),
    ]
